on: [push, pull_request]

jobs:
    build:
        strategy:
            matrix:
                os: [ubuntu-latest]
        runs-on: ${{ matrix.os }}
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name:  Setup Java JDK
              uses: actions/setup-java@v3
              with: 
                distribution: temurin
                java-version: 8
            - name: Make Build Executable
              run: chmod +x ./build.sh
            - name: Build
              run: ./build.sh
            - name: Collect Artifacts
              uses: actions/checkout@v3
              with:
                name: Build
                path: build/src/release/